[assembly: AssemblyTitle("ForagersDelight")]
[assembly: AssemblyCopyright("Sm4rtBoyTom")]
[assembly: AssemblyVersion("1.3.1")]
[assembly: AssemblyFileVersion("1.3.1")]
[assembly: MelonInfo(typeof(ForagersDelightMod.Main), "ForagersDelight", "1.3.1", "Sm4rtBoyTom", null)]
[assembly: MelonGame("Hinterland", "TheLongDark")]